from __future__ import annotations

from enum import Enum


class ErrorCode(str, Enum):
    """Unified application error codes (See error handling docs)."""

    # --- Request validation errors (4xx) ---
    AUTH_REQUIRED = "AUTH_REQUIRED"
    AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
    AUTH_SESSION_EXPIRED = "AUTH_SESSION_EXPIRED"
    AUTH_TOKEN_INVALID = "AUTH_TOKEN_INVALID"
    AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED"
    AUTH_EMAIL_ALREADY_EXISTS = "AUTH_EMAIL_ALREADY_EXISTS"
    INVALID_WORKFLOW = "INVALID_WORKFLOW"
    INVALID_NODE_CONFIG = "INVALID_NODE_CONFIG"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"
    FILE_QUOTA_EXCEEDED = "FILE_QUOTA_EXCEEDED"
    UNSUPPORTED_FORMAT = "UNSUPPORTED_FORMAT"
    WORKFLOW_NOT_FOUND = "WORKFLOW_NOT_FOUND"
    TASK_NOT_FOUND = "TASK_NOT_FOUND"
    TASK_RESULT_NOT_READY = "TASK_RESULT_NOT_READY"
    NODE_NOT_FOUND = "NODE_NOT_FOUND"
    DUPLICATE_WORKFLOW_VERSION = "DUPLICATE_WORKFLOW_VERSION"
    WORKFLOW_VERSION_CONFLICT = "WORKFLOW_VERSION_CONFLICT"
    WORKSPACE_NOT_FOUND = "WORKSPACE_NOT_FOUND"
    WORKSPACE_FORBIDDEN = "WORKSPACE_FORBIDDEN"
    WORKSPACE_NOT_EMPTY = "WORKSPACE_NOT_EMPTY"
    PROVIDER_NOT_FOUND = "PROVIDER_NOT_FOUND"
    FILE_NOT_FOUND = "FILE_NOT_FOUND"
    FILE_IN_USE = "FILE_IN_USE"
    FILE_CLEANUP_FAILED = "FILE_CLEANUP_FAILED"
    TEST_SET_NOT_FOUND = "TEST_SET_NOT_FOUND"
    TEST_SET_IN_USE = "TEST_SET_IN_USE"
    DOCUMENT_NOT_FOUND = "DOCUMENT_NOT_FOUND"
    DOCUMENT_IN_USE = "DOCUMENT_IN_USE"
    REQUIRED_CAPABILITY_MISSING = "REQUIRED_CAPABILITY_MISSING"
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    REQUEST_CONFLICT = "REQUEST_CONFLICT"
    REQUEST_VALIDATION_FAILED = "REQUEST_VALIDATION_FAILED"

    # --- Engine execution errors (5xx) ---
    ENGINE_TIMEOUT = "ENGINE_TIMEOUT"
    ENGINE_UNREACHABLE = "ENGINE_UNREACHABLE"
    ENGINE_INTERNAL_ERROR = "ENGINE_INTERNAL_ERROR"
    ENGINE_INVALID_RESPONSE = "ENGINE_INVALID_RESPONSE"
    ENGINE_RATE_LIMITED = "ENGINE_RATE_LIMITED"

    # --- Task orchestration errors ---
    TASK_CANCELLED = "TASK_CANCELLED"
    TASK_ALREADY_RUNNING = "TASK_ALREADY_RUNNING"
    NODE_NOT_FAILED = "NODE_NOT_FAILED"
    NODE_DEPENDENCY_FAILED = "NODE_DEPENDENCY_FAILED"
    WORKFLOW_CYCLE_DETECTED = "WORKFLOW_CYCLE_DETECTED"

    # --- Infrastructure errors ---
    DB_WRITE_FAILED = "DB_WRITE_FAILED"
    DB_READ_FAILED = "DB_READ_FAILED"
    REDIS_UNAVAILABLE = "REDIS_UNAVAILABLE"
    CELERY_WORKER_UNAVAILABLE = "CELERY_WORKER_UNAVAILABLE"
    STORAGE_FULL = "STORAGE_FULL"
    INTERNAL_ERROR = "INTERNAL_ERROR"


ERROR_CODE_STATUS_MAP: dict[ErrorCode, int] = {
    ErrorCode.AUTH_REQUIRED: 401,
    ErrorCode.AUTH_INVALID_CREDENTIALS: 401,
    ErrorCode.AUTH_SESSION_EXPIRED: 401,
    ErrorCode.AUTH_TOKEN_INVALID: 401,
    ErrorCode.AUTH_TOKEN_EXPIRED: 401,
    ErrorCode.AUTH_EMAIL_ALREADY_EXISTS: 409,
    ErrorCode.INVALID_WORKFLOW: 400,
    ErrorCode.INVALID_NODE_CONFIG: 422,
    ErrorCode.FILE_TOO_LARGE: 413,
    ErrorCode.FILE_QUOTA_EXCEEDED: 413,
    ErrorCode.UNSUPPORTED_FORMAT: 422,
    ErrorCode.WORKFLOW_NOT_FOUND: 404,
    ErrorCode.TASK_NOT_FOUND: 404,
    ErrorCode.TASK_RESULT_NOT_READY: 409,
    ErrorCode.NODE_NOT_FOUND: 404,
    ErrorCode.DUPLICATE_WORKFLOW_VERSION: 409,
    ErrorCode.WORKFLOW_VERSION_CONFLICT: 409,
    ErrorCode.WORKSPACE_NOT_FOUND: 404,
    ErrorCode.WORKSPACE_FORBIDDEN: 403,
    ErrorCode.WORKSPACE_NOT_EMPTY: 409,
    ErrorCode.PROVIDER_NOT_FOUND: 404,
    ErrorCode.FILE_NOT_FOUND: 404,
    ErrorCode.FILE_IN_USE: 409,
    ErrorCode.FILE_CLEANUP_FAILED: 503,
    ErrorCode.TEST_SET_NOT_FOUND: 404,
    ErrorCode.TEST_SET_IN_USE: 409,
    ErrorCode.DOCUMENT_NOT_FOUND: 404,
    ErrorCode.DOCUMENT_IN_USE: 409,
    ErrorCode.REQUIRED_CAPABILITY_MISSING: 403,
    ErrorCode.RESOURCE_NOT_FOUND: 404,
    ErrorCode.REQUEST_CONFLICT: 409,
    ErrorCode.REQUEST_VALIDATION_FAILED: 422,
    ErrorCode.ENGINE_TIMEOUT: 504,
    ErrorCode.ENGINE_UNREACHABLE: 503,
    ErrorCode.ENGINE_INTERNAL_ERROR: 500,
    ErrorCode.ENGINE_INVALID_RESPONSE: 502,
    ErrorCode.ENGINE_RATE_LIMITED: 503,
    ErrorCode.TASK_CANCELLED: 200,
    ErrorCode.TASK_ALREADY_RUNNING: 409,
    ErrorCode.NODE_NOT_FAILED: 409,
    ErrorCode.NODE_DEPENDENCY_FAILED: 500,
    ErrorCode.WORKFLOW_CYCLE_DETECTED: 400,
    ErrorCode.DB_WRITE_FAILED: 500,
    ErrorCode.DB_READ_FAILED: 500,
    ErrorCode.REDIS_UNAVAILABLE: 503,
    ErrorCode.CELERY_WORKER_UNAVAILABLE: 503,
    ErrorCode.STORAGE_FULL: 500,
    ErrorCode.INTERNAL_ERROR: 500,
}


def resolve_status_code(error_code: ErrorCode, default: int = 500) -> int:
    """Resolve HTTP status code from ErrorCode with fallback."""
    return ERROR_CODE_STATUS_MAP.get(error_code, default)
